import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import ThemeSwitcher from "./components/ThemeSwitcher/ThemeSwitcher";
import { AppWrapper } from "./context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.className}>
      <body className="bg-slate-300 dark:bg-slate-900">
        <Providers>
          <ThemeSwitcher />
          <AppWrapper>{children}</AppWrapper>
        </Providers>
      </body>
    </html>
  );
}
